CREATE TABLE TABLE_DATA_1
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_DATA_2
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_COLC
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');

INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');

select * from TABLE_colc
order by std_date;

merge into table_colc tc
using table_data_1 td1
on (tc.std_date = td1.create_date)
WHEN MATCHED THEN
    UPDATE SET tc.check_data1 = 'Y'
WHEN NOT MATCHED THEN
    INSERT VALUES (td1.create_date, 'Y', 'N');
    
merge into table_colc tc
using table_data_2 td2
on (tc.std_date = td2.create_date)
WHEN MATCHED THEN
    UPDATE SET tc.check_data2 = 'Y'
WHEN NOT MATCHED THEN
    INSERT VALUES (td2.create_date, 'N', 'Y');
    
DROP TABLE TABLE_COLC;

CREATE TABLE TABLE_COLC
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

INSERT INTO TABLE_DATA_1 VALUES (5, '2023-04-06');
INSERT INTO TABLE_DATA_2 VALUES (5, '2023-04-07');

